services:

  db:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: initial
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_ROOT_USERNAME: root
    volumes:
      - ./mongo-volume:/data/db
    ports:
       - 27017:27017

    
